server:
  port: 8052
spring:
  data:
    mongodb:
      database: bootcamp
      host: localhost
      port: 27017
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka
