server:
  port: 8053
spring:
  data:
    mongodb:
      database: bootcamp
      host: localhost
      port: 27017
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
